### ISSUE TITLE
Protocol documentation?

### ISSUE THREAD

**Issue by raintonr** [ken830/Hubitat#3]
I don't use Hubitat but am interested in creating an integration with ioBroker for HikVision events and stumbled across your code.

Am curious if you have any doco for this protocol that would be useful is all?

Thanks :)

**Comment by ken830** [comment]
Hi.. It's a bit of trial-and-error and reading through Hikvision's ISAPI document, which you should be able to find by just Googling. 

The camera is set-up to send events to the Hubitat, which is passively receiving a stream of data from the camera. What I get is just a bunch of data in XML that I parse through.

There is a way to interact with the camera API with a PUT, but due to limitations of Hubitat (or maybe my abilities -- I'm not very experienced in SW dev), I'm stuck with the above integration.

There's some discussion here: https://ipcamtalk.com/threads/figuring-out-hikvision-api-isapi.43619/

I hope that's somewhat useful. Sorry if not.

**Comment by raintonr** [comment]
Now I'm confused - not hard to do :wink:

I know about ISAPI and have the doco. But I thought ISAPI is for incoming connections to the camera only. Is that not the case?

I mean, you say the server is, "...passively receiving a stream of data from the camera." which implies one needs a server listening for connections, handling requests and sending an appropriate response so the camera thinks the alarm server is working.

I actually tried starting a dummy HTTP server on a host here and configured that host/port in the alarm server screen but looked like my camera (DS-2CD2143G2) was just making a connection but then never sent a request. Or any data at all after the socket connection which is very odd. Guess it's possible I messed something up in the logging :thinking:

Don't suppose you have a packet capture of your camera sending events and the responses necessary or anything like that?

**Comment by ken830** [comment]
Sorry... maybe some context is missing here. The intended usage for this driver code is described on the Hubitat forums:

[https://community.hubitat.com/t/release-hikvision-alarm-http-listening-data-streaming-alarm-server/64767](https://community.hubitat.com/t/release-hikvision-alarm-http-listening-data-streaming-alarm-server/64767)

Basically, the cameras are configured to simply send data to a "HTTP Listening" server by specifying a destination IP and port. Then events (motion, line crossing, etc.) are linked to the "Notify Surveillance Center" under "linkage method" which will trigger the camera to send data to the specified IP/port. No response from the listening server is expected.

**Comment by raintonr** [comment]
Ah, OK, thanks for that. It's a bit odd how there is no kind of handshake or whatever with this server, but guess for me it's easier to implement an integration into our system.

FWIW, because the camera is so 'dumb' you can just fire up netcat and look at the data it's sending. With this I get:

```POST / HTTP/1.1
Content-Type: application/xml; charset="UTF-8"
Host: 10.1.1.42
Connection: Keep-Alive
Content-Length: 744

<?xml version="1.0" encoding="UTF-8"?>
<EventNotificationAlert version="1.0" xmlns="urn:psialliance-org">
<ipAddress>x.x.x.x</ipAddress>
<protocol>HTTP</protocol>
<macAddress>44:a6:42:xx:xx:xx</macAddress>
<channelID>1</channelID>
<dateTime>2022-01-19T09:31:00+01:00</dateTime>
<activePostCount>1</activePostCount>
<eventType>VMD</eventType>
<eventState>active</eventState>
<eventDescription>Motion alarm</eventDescription>
<channelName>Camera 01</channelName>
<Extensions version="1.0" xmlns="urn:psialliance-org">
<serialNumber>DS-2CD2143G2-xxxxxxxxxxxxxxxxxxxxxx</serialNumber>
<eventPush>VMD&amp;&amp;DS-2CD2143G2-xxxxxxxxxxxxxxxxxxxxxx,2022-01-19T09:31:00+01:00,1,1.0</eventPush>
</Extensions>
</EventNotificationAlert>
```

So yeah. Just parse the post request without issuing a response and job done. Cheers :smile:
